### ISSUE TITLE
Temperature feedback program?

### ISSUE THREAD

**Issue by danmarwick** [GlasgowTeam3RTEP/Excellentea#11]
I see that the programs within the "tea" folder take in user defined temperatures and the programs within the "sensor" folder read in temperature through the 1-wire protocol.  There should be a method for controlling the temperature of the heating element based on these two variables.

Daniel - Team 13

**Comment by SimoneMarcigaglia** [comment]
I have now updated the main program files so that they take care of doing just that. Thanks for raising the issue.
