### ISSUE TITLE
Software Information

### ISSUE THREAD

**Issue by croaljack0** [GlasgowTeam3RTEP/Excellentea#6]
Further information about the software operation is required. i.e the different classes involved, number of threads of operation required.

** Team 10 **

**Comment by SimoneMarcigaglia** [comment]
Our [wiki](https://github.com/GlasgowTeam3RTEP/Excellentea/wiki) has now been updated with that information. The full software documentation can be found [here](https://glasgowteam3rtep.github.io/Excellentea/index.html). Thanks for raising the issue.
