### ISSUE TITLE
miss brief introduction about the code

### ISSUE THREAD

**Issue by jingwang9** [GlasgowTeam3RTEP/Excellentea#8]
I don't get the point about the code, need brief introduction about the sensor's function

team 6

**Comment by SimoneMarcigaglia** [comment]
A brief introduction of hardware and software can be found on our [wiki](https://github.com/GlasgowTeam3RTEP/Excellentea/wiki) and the full software documentation can be found [here](https://glasgowteam3rtep.github.io/Excellentea/). Thanks for raising the issue.
