### ISSUE TITLE
Miss code, and software information

### ISSUE THREAD

**Issue by Kenny840394191** [GlasgowTeam3RTEP/Excellentea#9]
I have not found your code, I think code will be required in your project. I hope to see more information about your sensors, will be better.

Team 15

**Comment by SimoneMarcigaglia** [comment]
The code is now up on github. More information can be found on our [wiki](https://github.com/GlasgowTeam3RTEP/Excellentea/wiki) and in the [software documentation](https://glasgowteam3rtep.github.io/Excellentea/). Thanks for raising the issue.
